<a href="https://colab.research.google.com/github/segzy01/Oluwasegun-Durowoju-Prework/blob/master/Data_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Fri Jul 28 06:40:13 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    25W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+



In this excercise you will use Python to query data from an open source REST API.  Then filter, join, and query the data.


Feel free to add cells and comments as needed. We expect this to take around 30 mins to complete.  If you get stuck and can't complete it in a reasonable amount of time just leave some notes & code showing your attempt.


When finished, be sure to **SAVE YOUR WORK** and let us know you're done!

##1. Using Python `requests` library, retrieve the WA state electric vehicle population data set from data.gov

Data.gov dataset: https://catalog.data.gov/dataset/electric-vehicle-population-data

Requests Docs: https://requests.readthedocs.io/en/latest/

In [ ]:
import requests
url = 'https://data.wa.gov/api/views/f6w7-q2d2/rows.csv?accessType=DOWNLOAD'

### START YOUR CODE HERE ###
# Send a GET request to the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Save the response content to a file
    with open('electric_vehicle_population.csv', 'wb') as file:
        file.write(response.content)
    print("Data downloaded successfully.")
else:
    print("Failed to retrieve the data. Check the URL or try again later.")

Data downloaded successfully.

## 2. Using `pandas` library, create a dataframe containing the data from above and display the first 10 rows

Hint: use StringIO to read the response data

Relevant Pandas Docs: https://pandas.pydata.org/docs/reference/io.html

In [ ]:
import pandas as pd
from io import StringIO

### START YOUR CODE HERE ###
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Create a StringIO object from the response content
    data = StringIO(response.text)

    # Create a DataFrame from the CSV data
    df = pd.read_csv(data)

    # Display the first 10 rows of the DataFrame
    print(df.head(10))
else:
    print("Failed to retrieve the data. Check the URL or try again later.")

   VIN (1-10)     County          City State  Postal Code  Model Year  \
0  1N4AZ0CP5D     Kitsap     Bremerton    WA      98310.0        2013
1  1N4AZ1CP8K     Kitsap  Port Orchard    WA      98366.0        2019
2  5YJXCAE28L       King       Seattle    WA      98199.0        2020
3  SADHC2S1XK   Thurston       Olympia    WA      98503.0        2019
4  JN1AZ0CP9B  Snohomish       Everett    WA      98204.0        2011
5  1G1RB6S58J     Yakima         Selah    WA      98942.0        2018
6  5YJ3E1EB7K    Spokane       Spokane    WA      99203.0        2019
7  3FA6P0SU5E   Thurston      Tumwater    WA      98501.0        2014
8  5YJ3E1EB3K  Snohomish       Everett    WA      98203.0        2019
9  1C4JJXP6XN     Kitsap  Port Orchard    WA      98366.0        2022

        Make     Model                   Electric Vehicle Type  \
0     NISSAN      LEAF          Battery Electric Vehicle (BEV)
1     NISSAN      LEAF          Battery Electric Vehicle (BEV)
2      TESLA   MODEL X          Battery Electric Vehicle (BEV)
3     JAGUAR    I-PACE          Battery Electric Vehicle (BEV)
4     NISSAN      LEAF          Battery Electric Vehicle (BEV)
5  CHEVROLET      VOLT  Plug-in Hybrid Electric Vehicle (PHEV)
6      TESLA   MODEL 3          Battery Electric Vehicle (BEV)
7       FORD    FUSION  Plug-in Hybrid Electric Vehicle (PHEV)
8      TESLA   MODEL 3          Battery Electric Vehicle (BEV)
9       JEEP  WRANGLER  Plug-in Hybrid Electric Vehicle (PHEV)

  Clean Alternative Fuel Vehicle (CAFV) Eligibility  Electric Range  \
0           Clean Alternative Fuel Vehicle Eligible              75
1           Clean Alternative Fuel Vehicle Eligible             150
2           Clean Alternative Fuel Vehicle Eligible             293
3           Clean Alternative Fuel Vehicle Eligible             234
4           Clean Alternative Fuel Vehicle Eligible              73
5           Clean Alternative Fuel Vehicle Eligible              53
6           Clean Alternative Fuel Vehicle Eligible             220
7             Not eligible due to low battery range              19
8           Clean Alternative Fuel Vehicle Eligible             220
9             Not eligible due to low battery range              21

   Base MSRP  Legislative District  DOL Vehicle ID  \
0          0                  23.0       214384901
1          0                  26.0       271008636
2          0                  36.0         8781552
3          0                   2.0         8308492
4          0                  21.0       245524527
5          0                  13.0       474699725
6          0                   6.0       241573384
7          0                  35.0       143101213
8          0                  38.0       209716587
9          0                  26.0       205776434

                                 Vehicle Location  \
0  POINT (-122.61136499999998 47.575195000000065)
1   POINT (-122.63926499999997 47.53730000000007)
2           POINT (-122.394185 47.63919500000003)
3                      POINT (-122.8285 47.03646)
4   POINT (-122.24128499999995 47.91088000000008)
5  POINT (-120.54187999999999 46.654175000000066)
6  POINT (-117.42526499999997 47.635365000000036)
7                    POINT (-122.89692 47.043535)
8   POINT (-122.21310499999998 47.95479000000006)
9   POINT (-122.63926499999997 47.53730000000007)

                               Electric Utility  2020 Census Tract
0                        PUGET SOUND ENERGY INC       5.303508e+10
1                        PUGET SOUND ENERGY INC       5.303509e+10
2  CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)       5.303301e+10
3                        PUGET SOUND ENERGY INC       5.306701e+10
4                        PUGET SOUND ENERGY INC       5.306104e+10
5                                    PACIFICORP       5.307700e+10
6                 MODERN ELECTRIC WATER COMPANY       5.306300e+10
7                        PUGET SOUND ENERGY INC       5.306701e+10
8                        PUGET SOUND ENERGY INC       5.306104e+10
9                        PUGET SOUND ENERGY INC       5.303509e+10

## 2.b. Format the 2020 Census Tract column as an integer

Replace non-numeric values in the column with pd.NA

Display the first 10 rows of the column

In [ ]:
### START YOUR CODE HERE ###
 # Specify the column you want to format as an integer
column_name = '2020 Census Tract'

# Convert the column to integer type and replace non-numeric values with pd.NA
df[column_name] = pd.to_numeric(df[column_name], errors='coerce').astype('Int64') #The pd.to_numeric() function is used to convert the values in the selected column to numeric type.
                                                                                  # .astype() method is used to further convert the column to the 'Int64' type
                                                                                  #When errors is set to 'coerce', it will replace non-numeric values with NaN (Not a Number).

# Display the first 10 rows of the updated column
df[column_name].head(10)

0    53035080400
1    53035092300
2    53033005600
3    53067011628
4    53061041901
5    53077003004
6    53063004200
7    53067011720
8    53061041601
9    53035092200
Name: 2020 Census Tract, dtype: Int64

## 3. Use `pandasql` to query the dataset

Pandasql allows you to query a dataframe using sqlite syntax.
Pandasql docs: https://pypi.org/project/pandasql/

The table name you SELECT from is the name of the variable you saved the dataframe to

In [ ]:
### RUN THIS TO INSTALL PANDASQL IN THIS NOTEBOOK ###
#!pip install SQLAlchemy==1.4.46
#!pip install pandasql
### THIS MAY REQUIRE A KERNEL RESTART ###
from pandasql import sqldf

# Specify the table name as the variable name of the DataFrame
table_name = 'df'

# Define the SQL query
query = "SELECT * FROM " + table_name

# Execute the SQL query using pandasql
result = sqldf(query, locals())

#display result
result

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,1N4AZ0CP5D,Kitsap,Bremerton,WA,98310.0,2013,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,75,0,23.0,214384901,POINT (-122.61136499999998 47.575195000000065),PUGET SOUND ENERGY INC,5.303508e+10
1,1N4AZ1CP8K,Kitsap,Port Orchard,WA,98366.0,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150,0,26.0,271008636,POINT (-122.63926499999997 47.53730000000007),PUGET SOUND ENERGY INC,5.303509e+10
2,5YJXCAE28L,King,Seattle,WA,98199.0,2020,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,293,0,36.0,8781552,POINT (-122.394185 47.63919500000003),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,SADHC2S1XK,Thurston,Olympia,WA,98503.0,2019,JAGUAR,I-PACE,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,234,0,2.0,8308492,POINT (-122.8285 47.03646),PUGET SOUND ENERGY INC,5.306701e+10
4,JN1AZ0CP9B,Snohomish,Everett,WA,98204.0,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73,0,21.0,245524527,POINT (-122.24128499999995 47.91088000000008),PUGET SOUND ENERGY INC,5.306104e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138774,KNAGV4LD6L,Clark,Vancouver,WA,98686.0,2020,KIA,OPTIMA,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,28,0,17.0,122272881,POINT (-122.64839529999995 45.70104270000007),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,5.301104e+10
138775,7SAYGDEE1N,Thurston,Lacey,WA,98503.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,22.0,187390038,POINT (-122.8285 47.03646),PUGET SOUND ENERGY INC,5.306701e+10
138776,5YJYGDEE7M,Benton,Richland,WA,99352.0,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,8.0,181300416,POINT (-119.29441499999996 46.27187500000008),BONNEVILLE POWER ADMINISTRATION||CITY OF RICHL...,5.300501e+10
138777,WBY33AW08P,Pierce,Tacoma,WA,98443.0,2023,BMW,I4,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,25.0,224612055,POINT (-122.36463499999996 47.19449000000003),BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...,5.305394e+10
138778,JN1AZ0CP2B,King,Seattle,WA,98118.0,2011,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,73,0,37.0,246621546,POINT (-122.28338999999994 47.549285000000054),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10

Example usage:

In [ ]:
from pandasql import sqldf

### EXAMPLE USE OF PANDASSQL ###
#query = '''SELECT DISTINCT County, "Electric Utility" FROM elec_veh_df''' # table name equals the variable name of your dataframe from 2
#sqldf(query, globals())

### 3.a Write a query to select the top 10 vehicle makes by average electric range.

Display the results below

In [ ]:
### YOUR CODE GOES HERE ###


# Define the SQL query to select top 10 vehicle makes by average electric range
query = f"""
SELECT "Make", AVG("Electric Range") AS AvgRange
FROM {table_name}
GROUP BY "Make"
ORDER BY AvgRange DESC
LIMIT 10
"""

    # Execute the SQL query using pandasql
result = sqldf(query, globals())

#Display Query
result

                   Make    AvgRange
0                JAGUAR  206.594595
1  WHEEGO ELECTRIC CARS  100.000000
2                 TH!NK  100.000000
3                 TESLA   97.349740
4             CHEVROLET   96.504676
5                NISSAN   86.507837
6                  FIAT   85.639364
7                 SMART   62.416667
8        AZURE DYNAMICS   56.000000
9                   KIA   55.369952

### 3.b. Retrieve WA state electric vehicle registration data and use pandasql to join it with electric vehicle population data.  Write a query to find all vehicles with over 100000 odometer reading ordered by desc model year.

Electric Vehicle Registration Data: https://catalog.data.gov/dataset/electric-vehicle-title-and-registration-activity

In [ ]:
veh_regs = 'https://data.wa.gov/api/views/rpr4-cgyd/rows.csv?accessType=DOWNLOAD'

### YOUR CODE GOES HERE ###
#step 1 retrieve electrivc vehicle registration data
import requests
urls = 'https://data.wa.gov/api/views/rpr4-cgyd/rows.csv?accessType=DOWNLOAD'
### START YOUR CODE HERE ###
# Send a GET request to the URL
responses = requests.get(urls)

# Check if the request was successful (status code 200)
if responses.status_code == 200:
    # Save the response content to a file
    with open('electric_vehicle_registration.csv', 'wb') as file: #change to registration instead of population
        file.write(responses.content) #change to responses
    print("Data downloaded successfully.")
else:
    print("Failed to retrieve the data. Check the URL or try again later.")

Data downloaded successfully.

In [ ]:
import pandas as pd
from io import StringIO

##Load to Dataframe

# Check if the request was successful (status code 200)
if responses.status_code == 200:
    # Create a StringIO object from the response content
    data_R = StringIO(responses.text)

    # Create a DataFrame from the CSV data
    df_Registration = pd.read_csv(data_R)
    df_Registration.head(10)

In [ ]:
df_population = df # parse df to df_population

In [ ]:
# rename the columns VIN
df_population.rename(columns={'VIN (1-10)': 'VIN'}, inplace=True) # Add these lines of code
df_Registration.rename(columns={'VIN (1-10)': 'VIN'}, inplace=True)

In [ ]:
# Step 3: Register the DataFrames in the SQL context
locals()["df_population"] = df_population
locals()["df_Registration"] = df_Registration  # Replace df_Registration with the actual DataFrame name

In [ ]:
#Write the join query based on common columns between the two DataFrames
query = """
SELECT *
FROM df_population p
INNER JOIN df_Registration r ON p.VIN = r.VIN
"""
# Execute the join query using pandasql
#df_result = sqldf(query, globals())

In [ ]:
 ##Write the Query to Find Vehicles with Over 100000 Odometer Reading
query = """
SELECT *
FROM df_result
WHERE OdometerReading > 100000
ORDER BY ModelYear DESC
"""
# Execute the query to get the final result
#final_result = sqldf(query, globals())

# Display the final result
#final_result